### ISSUE TITLE
Missing file 

### ISSUE THREAD

**Issue by VaibhavBhadre18** [prajwalk-1/Product-Catalog#3]
missing `requirements.txt` file

**Comment by NVS-PRAJWAL-KANADE** [comment]
I understand the issue regarding the missing `requirements.txt` file. Here's a brief overview of the project and how to get it running:


**Project Overview:** 
The project consists of three apps: **accounts**, **product**, and **product_catalog**. 


**Setup Instructions** 
1. **Install Django**: If you haven't installed Django yet, run the following command:
   ```bash
   pip install django
   ```

2. **Clone the Repository**: If you haven't already, clone the project repository:
   ```bash
   git clone https://github.com/prajwalk-1/Product-Catalogue-using-Django.git 
   ```

3. **Navigate to the Project Directory**:
   ```bash
   cd Product-Catalogue-using-Django
   ```

4. **Run Migrations**: Apply the database migrations:
   ```bash
   python manage.py migrate
   ```

5. **Run the Development Server**: Start the Django development server:
   ```bash
   python manage.py runserver
   ```

6. Access the Application
